config/routes.rb
Rails.application.routes.draw do
  resources :line_items
  resources :carts
  get 'wines/index'

  get 'wines/show'

  get 'wines/new'

  get 'wines/edit'

  get 'wines/create'

  get 'wines/update'

  get 'wines/destroy'

  get 'static_pages/home'

  get 'static_pages/help'

  get 'static_pages/about'

  get 'sessions/new'

  resources :users
  resources :wines

  root 'users#index'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

end

app/models/wine.rb
class Wine < ActiveRecord::Base
  validates_presence_of :name, :shortdesc, :longdesc, :grapetype, :forvegeterians, :origin, :bottlesize, :price, :supplier

  has_many :line_items
  
  before_destroy :ensure_not_referenced_by_any_line_item

  has_attached_file :photo, styles: { large: "600x600>", medium: "300x300>", thumb: "150x150#" }
  validates_attachment_content_type :photo,
                                      content_type: /\Aimage\/.*\Z/

  def self.search(search)
    if search
        self.where("name like ?", "%#{search}%")
    else
      self.all
    end
  end
  
  private
    #ensure no line items are referencing this wine product
    def ensure_not_referenced_by_any_line_item
      if line_items.empty?
        return true
      else
        errors.add(:base, 'Line items present')
      return false
      end
     end

  self.per_page = 2
end

app/controllers/wines_controller.rb
class WinesController < ApplicationController
  def index
     @wines = Wine.search(params[:search]).paginate(:page => params[:page])   
  end

  def show
   @wine = Wine.find(params[:id])
  end

  def new
    @wine = Wine.new
  end

  def edit
  end

  #POST /wines
  #POSER /wines.json
  def create
    @wine = Wine.new(wine_params)
    respond_to do |format|
    if @wine.save#try to save wine
        format.html { redirect_to(wine_url(@wine, page: @current_page),
                                  notice: 'Wine was successfully created.') }
        format.json { render action: 'show', status: :created, location: @wine }
      else
        format.html { render action: 'new' }
        format.json { render json: @wine.errors, status: :unprocessable_entity }
      end
    end
  end

   # No params from the internet, only allow the white list through.
  def wine_params
    params.require(:wine).permit(:name, :shortdesc, :longdesc, :grapetype, :forvegeterians, :origin, :bottlesize, :price, :supplier, :photo)
  end

    private
  def set_wine
    @wine = Wine.find(params[:id])
  end

  def update
  end

  def destroy
  end
end

app/helpers/wines_helper.rb
module WinesHelper
end

app/views/wines/_form.html.erb
<%= form_for(@wine, :html => { :multipart => true }) do |f| %>
  <% if @wine.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@wine.errors.count, "error") %> prohibited this wine from being saved:</h2>

      <ul>
      <% @wine.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <%= hidden_field_tag 'page', @current_page %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :shortdesc %><br>
    <%= f.text_field :shortdesc %>
  </div>
  <div class="field">
    <%= f.label :longdesc %><br>
    <%= f.text_field :longdesc %>
  </div>
  <div class="field">
    <%= f.label :grapetype %><br>
    <%= f.text_field :grapetype %>
  </div>
  <div class="field">
    <%= f.label :forvegeterians %><br>
    <%= f.check_box :forvegeterians %>
  </div>
  <div class="field">
    <%= f.label :origin %><br>
    <%= f.text_field :origin %>
  </div>
  <div class="field">
    <%= f.label :bottlesize %><br>
    <%= f.text_field :bottlesize %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.number_field :price, :class => 'text_field', :step => 'any' %>
  </div>
  <div class="field">
    <%= f.label :supplier %><br>
    <%= f.text_field :supplier %>
  </div>
  <div class="field">
    <%= f.file_field :photo %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/wines/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/wines/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/wines/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/wines/index.html.erb
<h1>Alcohol free wines</h1>
 
  <%= form_tag wines_path, :method => 'get' do %>
  <p>
  <%= text_field_tag :search, params[:search] %> 
  <%= submit_tag "Search", :name => nil %> 
  </p>

<% end %>

<% if @wines.length > 0 %>
    <table>
      <thead>
      <tr>
        <th>Name</th>
        <th>Short description</th>
        <th>Grape type</th>
        <th>Suitable for vegeterians</th>
        <th>Origin</th>
        <th>Bottle size</th>
        <th>Price</th>
        <th>Photo</th>
      </tr>
      </thead>
      <tbody>
      <% @wines.each do |wine| %>
          <tr>
            <td><%= wine.name %></td>
            <td><%= wine.shortdesc %></td>
            <td><%= wine.grapetype %></td>
            <td><%= wine.forvegeterians %></td>
            <td><%= wine.origin %></td>
            <td><%= wine.bottlesize %></td>
            <td><%= wine.price %></td>
            <td><%= image_tag(wine.photo, :size => "260x180") %></td>
            <div class="price_line">
              <span class="price"><%= number_to_currency(wine.price) %></span>
              <%= link_to 'Add to Cart', line_items_path(wine_id: wine), method: :post %>
            </div>
          </tr>
      <% end %>
      </tbody>
    </table>
<% end %>
<br/>
<div class="digg_pagination">
  <div>
    <%= page_entries_info @wines %>
  </div>
  <%= will_paginate @wines, container: false %>
</div>
<br/>

<%= link_to 'Add alcohol free wine', new_wine_path(page: @wines.current_page) %>

app/views/wines/new.html.erb
<h1>Add alcohol free wine</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path(page: @current_page) %>

app/views/wines/show.html.erb
<%= @wine.name %>

<%= @wine.longdesc %>

<%= @wine.grapetype %>

<%= @wine.forvegeterians %>

<%= @wine.origin %>

<%= @wine.bottlesize %>

<%= @wine.price %>

<%= @wine.supplier %>

<%= @wine.photo.url %>

<%= image_tag @wine.photo %>

app/views/wines/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>