config/routes.rb
Rails.application.routes.draw do
  resources :line_items
  resources :carts
  get 'wines/index'

  get 'wines/show'

  get 'wines/new'

  get 'wines/edit'

  get 'wines/create'

  get 'wines/update'

  get 'wines/destroy'

  get 'static_pages/home'

  get 'static_pages/help'

  get 'static_pages/about'

  get 'sessions/new'

  resources :users
  resources :wines

  root 'users#index'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Maf</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Help", '#' %></li>
        <li><%= link_to "Wines", wines_path %></li>
        <% if logged_in? %>
              <li>
                <%= link_to "Log out", logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

<%= yield %>
  <footer class="footer">
  <nav>
    <ul>
      <li><%= link_to "About",   '#' %></li>
    </ul>
  </nav>
</footer>

</body>
</html>